sudo: false
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"
services:
  - postgresql
before_script:
  - psql -c "create role drafter with login password 'crafter' createdb;" -U postgres
install: pip install tox-travis
script: tox
